spring:
  application:
    name: user
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9090/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always